name: fujiten
description: Japanese dictionary made with flutter

version: 1.0.5+6

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.3.0
  shared_preferences: ^2.2.0
  package_info_plus: ^8.0.0
  kana_kit: ^2.0.0
  path: ^1.8.0
  file_picker: ^8.0.0
  flutter_bloc: ^8.1.1
  path_provider: ^2.1.0
  dio: ^5.3.0
  archive: ^3.4.0

dev_dependencies:
  test: ^1.16.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
