name: fujiten
description: Japanese dictionary made with flutter

version: 1.0.3+4

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.1.0
  shared_preferences: ^2.0.8
  package_info_plus: ^4.0.1
  kana_kit: ^2.0.0
  path: ^1.8.0
  file_picker: ^5.3.1
  flutter_bloc: ^8.1.1
  path_provider: ^2.0.11
  dio: ^5.1.2
  archive: ^3.3.1

dev_dependencies:
  test: ^1.16.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
