name: fujiten
description: Offline Japanese dictionary made with flutter

version: 3.1.0+16

environment:
  sdk: ^3.13.4

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.4.0
  sqflite_common_ffi: ^2.4.2
  shared_preferences: ^2.2.0
  package_info_plus: ^10.2.0
  kana_kit: ^2.0.0
  path: ^1.8.0
  file_picker: ^13.1.0
  flutter_bloc: ^9.1.1
  path_provider: ^2.1.6
  dio: ^5.11.0
  archive: ^4.4.0
  equatable: ^3.0.0
  flutter_furigana_text: ^0.0.4
  flutter_kanjivg: ^0.1.1
  dynamic_color: ^2.1.0
  flutter_colorpicker: ^1.1.0
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  test: ^1.16.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true