name: fujiten
description: Offline Japanese dictionary made with flutter

version: 2.0.0+11

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.3.0
  shared_preferences: ^2.2.0
  package_info_plus: ^9.0.0
  kana_kit: ^2.0.0
  path: ^1.8.0
  file_picker: ^10.3.3
  flutter_bloc: ^9.1.1
  path_provider: ^2.1.0
  dio: ^5.9.0
  archive: ^4.0.7
  equatable: ^2.0.7
  kanji_drawing_animation: ^0.5.0+1
  ruby_text: ^3.0.3

dev_dependencies:
  sqflite_common_ffi: ^2.3.6
  test: ^1.16.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
