name: fujiten
description: Japanese dictionary made with flutter

version: 1.0.3+4

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.1.0
  shared_preferences: ^2.0.8
  package_info_plus: ^2.0.0
  kana_kit: ^2.0.0
  path: ^1.8.0
  file_picker: ^5.2.0
  flutter_bloc: ^8.1.1
  path_provider: ^2.0.11
  dio: ^4.0.6
  archive: ^3.3.1

dev_dependencies:
  test: ^1.16.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
