name: japanese_dictionary
description: Japanese expressions and kanji search

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.0.0
  shared_preferences: ^2.0.8
  ruby_text: ^3.0.1
  package_info_plus: ^1.3.0
  kana_kit: ^2.0.0
  path: ^1.8.0
  file_picker: ^5.0.0
  flutter_bloc: ^8.1.1

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  test: ^1.16.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true